import pandas as pd
df = pd.read_csv("data/herg.csv")
print("Dataset loaded successfully!!")
print()
print("Shape:")
print(df.shape)
print()
print("Columns:")
print(df.columns.tolist())
print()
print("First Five rows:")
print(df.head())
print()
print("Class distribution:")
print(df["Y"].value_counts())